# Thread 2: Gender Injustice

### This thread looks at the crimes against women in the past decade and concludes important pointers from it. For ex- how the rate of crime against women is affected each year, whether criminals are convicted, etc.

## EDA

# 01. Importing libraries

In [62]:
import pandas as pd
import sys
sys.path.append("..")

import utility as u

# 02. EDA on each file before using it for analysis

### a) Crime against women (2001-2022).csv

In [63]:
# this file uses wide format, we will first convert it into long format

df= u.load_data("data/Crime against Women (2001-2022).csv")
csv1= u.wide_to_long(df=df, id_cols="CRIME HEAD", value_name="cases", var_name="year")

In [64]:
u.eda(df=csv1)

  DataFrame
Shape       : 242 rows × 3 cols

Dtypes:
CRIME HEAD    object
year          object
cases          int64

Null counts:
CRIME HEAD    0
year          0
cases         0

Null %:
CRIME HEAD    0.0
year          0.0
cases         0.0

Sample:
                                  CRIME HEAD  year  cases
0                                       Rape  2001  16075
1  Kidnapping and Abduction of Women & Girls  2001  14645
2                               Dowry Deaths  2001   6851

In [65]:
u.missing_report(df=csv1)

  DataFrame
Shape       : 242 rows × 3 cols

             dtype  null_count  null_% flag
CRIME HEAD  object           0     0.0
year        object           0     0.0
cases        int64           0     0.0

No columns exceed 50% null threshold.

--> No nulls in the dataset

### b) combined_crime_against_women_full.csv

In [66]:
csv2= u.load_data("data/combined_crime_against_women_full.csv")

In [67]:
csv2.head

<bound method NDFrame.head of       Year           State_UT   State_UT_Raw   Row_Type  \
0     2001  All India (Total)      All India  Aggregate
1     2001  All India (Total)      All India  Aggregate
2     2001  All India (Total)      ALL INDIA  Aggregate
3     2001  All India (Total)      All India  Aggregate
4     2001  All India (Total)      All India  Aggregate
...    ...                ...            ...        ...
6328  2025          Telangana      Telangana   State/UT
6329  2025            Tripura        Tripura   State/UT
6330  2025      Uttar Pradesh  Uttar Pradesh   State/UT
6331  2025        Uttarakhand    Uttarakhand   State/UT
6332  2025        West Bengal    West Bengal   State/UT

                                Crime_Head_Standardized  \
0       Assault on Women with Intent to Outrage Modesty
1                       Cruelty by Husband or Relatives
2                                          Dowry Deaths
3                      Immoral Traffic (Prevention) Act
4     Indecent Representation of Women (Prevention) Act
...                                                 ...
6328                         Total Crimes against Women
6329                         Total Crimes against Women
6330                         Total Crimes against Women
6331                         Total Crimes against Women
6332                         Total Crimes against Women

                                         Crime_Head_Raw  \
0     ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...
1                       CRUELTY BY HUSBAND OR RELATIVES
2                                           DOWRY DEATH
3                        IMMORAL TRAFFIC(PREVENTION)ACT
4       INDECENT REPRESENTATION OF WOMEN(PREVENTION)ACT
...                                                 ...
6328                          TOTAL CRIME AGAINST WOMEN
6329                          TOTAL CRIME AGAINST WOMEN
6330                          TOTAL CRIME AGAINST WOMEN
6331                          TOTAL CRIME AGAINST WOMEN
6332                          TOTAL CRIME AGAINST WOMEN

      Is_Detailed_Subcategory    Count
0                       False  34124.0
1                       False  49170.0
2                       False   6851.0
3                       False   8796.0
4                       False   1052.0
...                       ...      ...
6328                    False      NaN
6329                    False      NaN
6330                    False      NaN
6331                    False      NaN
6332                    False      NaN

[6333 rows x 8 columns]>

In [68]:
u.eda(csv2)

  DataFrame
Shape       : 6333 rows × 8 cols

Dtypes:
Year                         int64
State_UT                    object
State_UT_Raw                object
Row_Type                    object
Crime_Head_Standardized     object
Crime_Head_Raw              object
Is_Detailed_Subcategory       bool
Count                      float64

Null counts:
Year                         0
State_UT                     0
State_UT_Raw                 0
Row_Type                     0
Crime_Head_Standardized    975
Crime_Head_Raw               0
Is_Detailed_Subcategory      0
Count                      116

Null %:
Year                        0.00
State_UT                    0.00
State_UT_Raw                0.00
Row_Type                    0.00
Crime_Head_Standardized    15.40
Crime_Head_Raw              0.00
Is_Detailed_Subcategory     0.00
Count                       1.83

Sample:
   Year           State_UT State_UT_Raw   Row_Type                          Crime_Head_Standardized                                       Crime_Head_Raw  Is_Detailed_Subcategory    Count
0  2001  All India (Total)    All India  Aggregate  Assault on Women with Intent to Outrage Modesty  ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY                    False  34124.0
1  2001  All India (Total)    All India  Aggregate                  Cruelty by Husband or Relatives                      CRUELTY BY HUSBAND OR RELATIVES                    False  49170.0
2  2001  All India (Total)    ALL INDIA  Aggregate                                     Dowry Deaths                                          DOWRY DEATH                    False   6851.0

In [69]:
u.missing_report(csv2)

  DataFrame
Shape       : 6333 rows × 8 cols

                           dtype  null_count  null_% flag
Year                       int64           0    0.00
State_UT                  object           0    0.00
State_UT_Raw              object           0    0.00
Row_Type                  object           0    0.00
Crime_Head_Standardized   object         975   15.40
Crime_Head_Raw            object           0    0.00
Is_Detailed_Subcategory     bool           0    0.00
Count                    float64         116    1.83

No columns exceed 50% null threshold.

In [71]:
csv2 = csv2[csv2["Row_Type"] == "State/UT"].reset_index(drop=True)
csv2.head(10)

,Year,State_UT,State_UT_Raw,Row_Type,Crime_Head_Standardized,Crime_Head_Raw,Is_Detailed_Subcategory,Count
0,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Assault on Women with Intent to Outrage Modesty,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...,False,19.0
1,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Cruelty by Husband or Relatives,CRUELTY BY HUSBAND OR RELATIVES,False,9.0
2,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Dowry Deaths,DOWRY DEATH,False,0.0
3,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Immoral Traffic (Prevention) Act,IMMORAL TRAFFIC(PREVENTION)ACT,False,0.0
4,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Indecent Representation of Women (Prevention) Act,INDECENT REPRESENTATION OF WOMEN(PREVENTION)ACT,False,0.0
5,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Insult to Modesty of Women,INSULT TO THE MODESTY OF WOMEN,False,1.0
6,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Kidnapping & Abduction of Women,KIDNAPPING & ABDUCTION,False,2.0
7,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Rape,RAPE,False,3.0
8,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Total Crimes against Women,TOTAL CRIMES AGAINST WOMEN,False,34.0
9,2001,Andhra Pradesh,Andhra Pradesh,State/UT,Assault on Women with Intent to Outrage Modesty,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...,False,3544.0

In [72]:
csv2["State_UT"].unique()

array(['Andaman & Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh',
       'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh',
       'Dadra & Nagar Haveli (pre-2020, separate UT)',
       'Daman & Diu (pre-2020, separate UT)', 'Delhi', 'Goa', 'Gujarat',
       'Haryana', 'Himachal Pradesh', 'Jammu & Kashmir', 'Jharkhand',
       'Karnataka', 'Kerala', 'Lakshadweep', 'Madhya Pradesh',
       'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland',
       'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim',
       'Tamil Nadu', 'Tripura', 'Uttar Pradesh', 'Uttarakhand',
       'West Bengal', 'Telangana', 'Dadra & Nagar Haveli and Daman & Diu',
       'Ladakh'], dtype=object)

Dadra & Nagar Haveli and Daman & Diu appear as separate entities pre-2020 and merged post-2020 due to the 2020 reorganisation. Will be handled in cleaning.

In [73]:
print(csv2["Year"].unique())
print(csv2["Year"].min(), "-", csv2["Year"].max())

[2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014
 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025]
2001 - 2025

The datasets looks at the crimes committed across more than a decade. 

From 2001-2025

In [76]:
csv2[csv2["Crime_Head_Standardized"].isna()][["Year","State_UT","Crime_Head_Raw"]].drop_duplicates().head(15)

,Year,State_UT,Crime_Head_Raw
4201,2014,Andaman & Nicobar Islands,1.1 - Custodial Rape
4202,2014,Andaman & Nicobar Islands,1.1.1 - Custodial_Gang Rape
4203,2014,Andaman & Nicobar Islands,1.1.2 - Custodial_Other Rape
4204,2014,Andaman & Nicobar Islands,1.2 - Rape other than Custodial
4205,2014,Andaman & Nicobar Islands,1.2.1 - Rape_Gang Rape
4206,2014,Andaman & Nicobar Islands,1.2.2 - Rape_Others
4212,2014,Andaman & Nicobar Islands,14.1 - Under ITP Section 5
4213,2014,Andaman & Nicobar Islands,14.2 - Under ITP Section 6
4214,2014,Andaman & Nicobar Islands,14.3 - Under ITP Section 7
4215,2014,Andaman & Nicobar Islands,14.4 - Under ITP Section 8
4216,2014,Andaman & Nicobar Islands,14.5 - Other Sections under ITP Act
4220,2014,Andaman & Nicobar Islands,3.1 - Kidnaping & Abduction Section 363 IPC
4221,2014,Andaman & Nicobar Islands,3.2 - Kidnaping & Abduction in order to Murder...
4222,2014,Andaman & Nicobar Islands,3.3 - Kidnapping for Ransom Section 364A
4223,2014,Andaman & Nicobar Islands,3.4 - Kidnapping & Abduction of Women to compe...

In [75]:
csv2[csv2["Count"].isna()][["Year","State_UT","Crime_Head_Standardized"]].head(20)

      Year                              State_UT     Crime_Head_Standardized
5657  2015                                Ladakh  Total Crimes against Women
5693  2016                                Ladakh  Total Crimes against Women
5729  2017                                Ladakh  Total Crimes against Women
5765  2018                                Ladakh  Total Crimes against Women
5801  2019                                Ladakh  Total Crimes against Women
5928  2023             Andaman & Nicobar Islands  Total Crimes against Women
5929  2023                        Andhra Pradesh  Total Crimes against Women
5930  2023                     Arunachal Pradesh  Total Crimes against Women
5931  2023                                 Assam  Total Crimes against Women
5932  2023                                 Bihar  Total Crimes against Women
5933  2023                            Chandigarh  Total Crimes against Women
5934  2023                          Chhattisgarh  Total Crimes against Women
5935  2023  Dadra & Nagar Haveli and Daman & Diu  Total Crimes against Women
5936  2023                                 Delhi  Total Crimes against Women
5937  2023                                   Goa  Total Crimes against Women
5938  2023                               Gujarat  Total Crimes against Women
5939  2023                               Haryana  Total Crimes against Women
5940  2023                      Himachal Pradesh  Total Crimes against Women
5941  2023                       Jammu & Kashmir  Total Crimes against Women
5942  2023                             Jharkhand  Total Crimes against Women

In [79]:
csv2.groupby("Year")["Count"].apply(lambda x: x.isna().sum())

Year
2001     0
2002     0
2003     0
2004     0
2005     0
2006     0
2007     0
2008     0
2009     0
2010     0
2011     0
2012     0
2013     0
2014     0
2015     1
2016     1
2017     1
2018     1
2019     1
2020     0
2021     0
2022     0
2023    31
2024    36
2025    36
Name: Count, dtype: int64

In [80]:

# confirm Is_Detailed_Subcategory accounts for the standardized nulls
csv2[csv2["Is_Detailed_Subcategory"] == True].shape  # should be ~975

(900, 8)