# Thread 2: Gender Injustice

### This thread looks at the crimes against women in the past decade and concludes important pointers from it. For ex- how the rate of crime against women is affected each year, whether criminals are convicted, etc.

## Cleaning

# 01. Import libraries

In [76]:
import pandas as pd
import sys
sys.path.append("..")

import utility as u

import importlib
importlib.reload(u)

# 02. Cleaning each file before using it for analysis

    NOTE

--> All the files will be loaded from `data/cleaned` (output from 01_EDA)

## a. file1.csv

In [77]:
# load the file
csv1= u.load_data("data/cleaned/file1.csv")

In [78]:
csv1.head(5)

                                          CRIME HEAD  year  cases
0                                               Rape  2001  16075
1          Kidnapping and Abduction of Women & Girls  2001  14645
2                                       Dowry Deaths  2001   6851
3  Assault on women with intent to outrage her mo...  2001  34124
4                     Insult to the modesty of Women  2001   9746

In [79]:
# checking the datatypes of all columns
u.eda(csv1)

=== DataFrame ===
Shape       : 242 rows × 3 cols
Duplicates  : 0

Column Summary:
             Dtype  Nulls  Null %  Uniques Flag
CRIME HEAD  object      0     0.0       11
year         int64      0     0.0       22
cases        int64      0     0.0      237

Numeric Stats:
          min       max      mean   median
year   2001.0    2022.0   2011.50   2011.5
cases     1.0  370616.0  45496.25  10277.5

Sample:
                                  CRIME HEAD  year  cases
0                                       Rape  2001  16075
1  Kidnapping and Abduction of Women & Girls  2001  14645
2                               Dowry Deaths  2001   6851

All datatypes are correct and need no changes. 

**file1 or csv1 is ready for 03_Analysis.**

## b. file2.csv

In [80]:
# load the file
csv2= u.load_data("data/cleaned/file2.csv")
csv2.head(5)

,Year,State_UT,State_UT_Raw,Row_Type,Crime_Head_Standardized,Crime_Head_Raw,Is_Detailed_Subcategory,Count
0,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Assault on Women with Intent to Outrage Modesty,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...,False,19.0
1,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Cruelty by Husband or Relatives,CRUELTY BY HUSBAND OR RELATIVES,False,9.0
2,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Dowry Deaths,DOWRY DEATH,False,0.0
3,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Immoral Traffic (Prevention) Act,IMMORAL TRAFFIC(PREVENTION)ACT,False,0.0
4,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Indecent Representation of Women (Prevention) Act,INDECENT REPRESENTATION OF WOMEN(PREVENTION)ACT,False,0.0

In [81]:
# checking the datatypes of all columns
u.eda(csv2)

=== DataFrame ===
Shape       : 5473 rows × 8 cols
Duplicates  : 0

Column Summary:
                           Dtype  Nulls  Null %  Uniques Flag
Year                       int64      0    0.00       25
State_UT                  object      0    0.00       38
State_UT_Raw              object      0    0.00       39
Row_Type                  object      0    0.00        1
Crime_Head_Standardized   object    900   16.44       15
Crime_Head_Raw            object      0    0.00       57
Is_Detailed_Subcategory     bool      0    0.00        2
Count                    float64    108    1.97     1581

Numeric Stats:
          min      max     mean  median
Year   2001.0   2025.0  2009.76  2010.0
Count     0.0  66381.0  1151.52    33.0

Sample:
   Year                   State_UT State_UT_Raw  Row_Type                          Crime_Head_Standardized                                       Crime_Head_Raw  Is_Detailed_Subcategory  Count
0  2001  Andaman & Nicobar Islands  A&N Islands  State/UT  Assault on Women with Intent to Outrage Modesty  ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY                    False   19.0
1  2001  Andaman & Nicobar Islands  A&N Islands  State/UT                  Cruelty by Husband or Relatives                      CRUELTY BY HUSBAND OR RELATIVES                    False    9.0
2  2001  Andaman & Nicobar Islands  A&N Islands  State/UT                                     Dowry Deaths                                          DOWRY DEATH                    False    0.0

In [82]:
csv2['Crime_Head_Standardized'].unique()

array(['Assault on Women with Intent to Outrage Modesty',
       'Cruelty by Husband or Relatives', 'Dowry Deaths',
       'Immoral Traffic (Prevention) Act',
       'Indecent Representation of Women (Prevention) Act',
       'Insult to Modesty of Women', 'Kidnapping & Abduction of Women',
       'Rape', 'Commission of Sati (Prevention) Act',
       'Dowry Prohibition Act',
       'Importation of Girls from Foreign Country', nan,
       'Protection of Women from Domestic Violence Act',
       'Attempt to Commit Rape', 'Abetment of Suicide of Women',
       'Total Crimes against Women'], dtype=object)

In [83]:
# creating a standardized crime column to replace raw one
# removing existing standardized col as it contains a large amount of nulls which will hinder dataset integrity.

csv2 = csv2.drop(columns=['Crime_Head_Standardized'])
csv2.head(3)

,Year,State_UT,State_UT_Raw,Row_Type,Crime_Head_Raw,Is_Detailed_Subcategory,Count
0,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...,False,19.0
1,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,CRUELTY BY HUSBAND OR RELATIVES,False,9.0
2,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,DOWRY DEATH,False,0.0

In [84]:
# creating a new standardized crime col and then dropping the raw col

csv2= u.standardize_crime_data(csv2, 'Crime_Head_Raw')

In [85]:
csv2.head(3)

,Year,State_UT,State_UT_Raw,Row_Type,Crime_Head_Raw,Is_Detailed_Subcategory,Count,Crime_Head_Standardized,Crime_Head_Subcategory
0,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...,False,19.0,Assault & Sexual Harassment,Assault to Outrage Modesty
1,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,CRUELTY BY HUSBAND OR RELATIVES,False,9.0,Cruelty & Dowry Offenses,Cruelty by Husband/Relatives
2,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,DOWRY DEATH,False,0.0,Cruelty & Dowry Offenses,Dowry Death

In [86]:
csv2['Crime_Head_Standardized'].unique()

array(['Assault & Sexual Harassment', 'Cruelty & Dowry Offenses',
       'Human Trafficking', 'Special & Local Laws',
       'Kidnapping & Abduction', 'Rape & Attempted Rape',
       'Others / Unclassified'], dtype=object)

In [87]:
csv2= csv2.drop(columns= ["Crime_Head_Raw", "Row_Type", "State_UT_Raw"])
csv2.head(3)

,Year,State_UT,Is_Detailed_Subcategory,Count,Crime_Head_Standardized,Crime_Head_Subcategory
0,2001,Andaman & Nicobar Islands,False,19.0,Assault & Sexual Harassment,Assault to Outrage Modesty
1,2001,Andaman & Nicobar Islands,False,9.0,Cruelty & Dowry Offenses,Cruelty by Husband/Relatives
2,2001,Andaman & Nicobar Islands,False,0.0,Cruelty & Dowry Offenses,Dowry Death

In [88]:
csv2= u.fill_numeric_nulls(csv2, ["Count"])

In [89]:
u.save_clean(csv2, "data/cleaned/file2.csv")

Saved | shape- (5473, 6)

## c. file3.csv

In [90]:
# upload the file
csv3= u.load_data("data/cleaned/file3.csv")
csv3.head(10)

,State/UT,Cases Pending Trial from the Previous Year - ( Col. 3),Cases Sent for Trial during the year - ( Col. 4),Total Cases for Trial (Col.3+Col.4) - ( Col. 5),Cases Convicted (Col.13+Col.14) - ( Col. 15),Cases Discharged - ( Col. 16),Cases Acquitted - ( Col. 17),Cases in which Trials were Completed (Col.15+Col.16+ Col.17) - ( Col. 18),Cases Pending Trial at End of the Year (Col.5-Col.19) - ( Col. 20),Conviction Rate (Col.15/Col.18)*100 - ( Col. 21),Pendency Percentage (Col.20/Col.5)*100 - ( Col. 22)
0,Andhra Pradesh,59575,21180,80755,553,142,8855,9550,63674,5.8,78.8
1,Arunachal Pradesh,3137,255,3392,24,8,38,70,3295,34.3,97.1
2,Assam,90075,11192,101267,732,36,9066,9834,78892,7.4,77.9
3,Bihar,115796,17370,133166,1285,65,932,2282,130546,56.3,98.0
4,Chhattisgarh,34270,5931,40201,964,625,2777,4366,35605,22.1,88.6
5,Goa,1811,204,2015,14,9,111,134,1864,10.4,92.5
6,Gujarat,98357,6855,105212,476,180,6531,7187,97926,6.6,93.1
7,Haryana,41260,8987,50247,818,29,5159,6006,44014,13.6,87.6
8,Himachal Pradesh,9370,1146,10516,136,5,707,848,9466,16.0,90.0
9,Jharkhand,30019,6353,36372,1684,29,3781,5494,30796,30.7,84.7