# Thread 2: Gender Injustice

### This thread looks at the crimes against women in the past decade and concludes important pointers from it. For ex- how the rate of crime against women is affected each year, whether criminals are convicted, etc.

## Cleaning

# 01. Import libraries

In [203]:
import pandas as pd
import sys
sys.path.append("..")

import utility as u

import importlib
importlib.reload(u)

# 02. Cleaning each file before using it for analysis

    NOTE

--> All the files will be loaded from `data/cleaned` (output from 01_EDA)

## a. file1.csv

In [204]:
# load the file
csv1= u.load_data("data/cleaned/file1.csv")

In [205]:
csv1.head(5)

                                          CRIME HEAD  year  cases
0                                               Rape  2001  16075
1          Kidnapping and Abduction of Women & Girls  2001  14645
2                                       Dowry Deaths  2001   6851
3  Assault on women with intent to outrage her mo...  2001  34124
4                     Insult to the modesty of Women  2001   9746

In [206]:
# checking the datatypes of all columns
u.eda(csv1)

=== DataFrame ===
Shape       : 242 rows × 3 cols
Duplicates  : 0

Column Summary:
             Dtype  Nulls  Null %  Uniques Flag
CRIME HEAD  object      0     0.0       11
year         int64      0     0.0       22
cases        int64      0     0.0      237

Numeric Stats:
          min       max      mean   median
year   2001.0    2022.0   2011.50   2011.5
cases     1.0  370616.0  45496.25  10277.5

Sample:
                                  CRIME HEAD  year  cases
0                                       Rape  2001  16075
1  Kidnapping and Abduction of Women & Girls  2001  14645
2                               Dowry Deaths  2001   6851

In [207]:
csv1['CRIME HEAD'].unique()

array(['Rape', 'Kidnapping and Abduction of Women & Girls',
       'Dowry Deaths',
       'Assault on women with intent to outrage her modesty',
       'Insult to the modesty of Women',
       'Cruelty by Husband or his relatives',
       'Importation of Girls from Foreign Country',
       'Immoral Traffic (P) Act', 'Dowry Prohibition Act',
       'Indecent Representation of Women (P) Act',
       'Total Crimes against Women'], dtype=object)

In [208]:
csv1= u.drop_totals(csv1, "CRIME HEAD", keywords=["Total Crimes against Women"])

Dropped 22 aggregate rows from 'CRIME HEAD'

In [209]:
csv1['CRIME HEAD'].unique()

array(['Rape', 'Kidnapping and Abduction of Women & Girls',
       'Dowry Deaths',
       'Assault on women with intent to outrage her modesty',
       'Insult to the modesty of Women',
       'Cruelty by Husband or his relatives',
       'Importation of Girls from Foreign Country',
       'Immoral Traffic (P) Act', 'Dowry Prohibition Act',
       'Indecent Representation of Women (P) Act'], dtype=object)

In [210]:
u.save_clean(csv1, "data/cleaned/file1.csv")

Saved | shape- (220, 3)

All datatypes are correct and need no changes. 

**file1 or csv1 is ready for 03_Analysis.**

## b. file2.csv

In [211]:
# load the file
csv2= u.load_data("data/cleaned/file2.csv")
csv2.head(5)

,Year,State_UT,State_UT_Raw,Row_Type,Crime_Head_Standardized,Crime_Head_Raw,Is_Detailed_Subcategory,Count
0,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Assault on Women with Intent to Outrage Modesty,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...,False,19.0
1,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Cruelty by Husband or Relatives,CRUELTY BY HUSBAND OR RELATIVES,False,9.0
2,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Dowry Deaths,DOWRY DEATH,False,0.0
3,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Immoral Traffic (Prevention) Act,IMMORAL TRAFFIC(PREVENTION)ACT,False,0.0
4,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Indecent Representation of Women (Prevention) Act,INDECENT REPRESENTATION OF WOMEN(PREVENTION)ACT,False,0.0

In [212]:
# checking the datatypes of all columns
u.eda(csv2)

=== DataFrame ===
Shape       : 5473 rows × 8 cols
Duplicates  : 0

Column Summary:
                           Dtype  Nulls  Null %  Uniques Flag
Year                       int64      0    0.00       25
State_UT                  object      0    0.00       38
State_UT_Raw              object      0    0.00       39
Row_Type                  object      0    0.00        1
Crime_Head_Standardized   object    900   16.44       15
Crime_Head_Raw            object      0    0.00       57
Is_Detailed_Subcategory     bool      0    0.00        2
Count                    float64    108    1.97     1581

Numeric Stats:
          min      max     mean  median
Year   2001.0   2025.0  2009.76  2010.0
Count     0.0  66381.0  1151.52    33.0

Sample:
   Year                   State_UT State_UT_Raw  Row_Type                          Crime_Head_Standardized                                       Crime_Head_Raw  Is_Detailed_Subcategory  Count
0  2001  Andaman & Nicobar Islands  A&N Islands  State/UT  Assault on Women with Intent to Outrage Modesty  ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY                    False   19.0
1  2001  Andaman & Nicobar Islands  A&N Islands  State/UT                  Cruelty by Husband or Relatives                      CRUELTY BY HUSBAND OR RELATIVES                    False    9.0
2  2001  Andaman & Nicobar Islands  A&N Islands  State/UT                                     Dowry Deaths                                          DOWRY DEATH                    False    0.0

In [213]:
csv2['Crime_Head_Standardized'].unique()

array(['Assault on Women with Intent to Outrage Modesty',
       'Cruelty by Husband or Relatives', 'Dowry Deaths',
       'Immoral Traffic (Prevention) Act',
       'Indecent Representation of Women (Prevention) Act',
       'Insult to Modesty of Women', 'Kidnapping & Abduction of Women',
       'Rape', 'Commission of Sati (Prevention) Act',
       'Dowry Prohibition Act',
       'Importation of Girls from Foreign Country', nan,
       'Protection of Women from Domestic Violence Act',
       'Attempt to Commit Rape', 'Abetment of Suicide of Women',
       'Total Crimes against Women'], dtype=object)

In [214]:
# creating a standardized crime column to replace raw one
# removing existing standardized col as it contains a large amount of nulls which will hinder dataset integrity.

csv2 = csv2.drop(columns=['Crime_Head_Standardized'])
csv2.head(3)

,Year,State_UT,State_UT_Raw,Row_Type,Crime_Head_Raw,Is_Detailed_Subcategory,Count
0,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...,False,19.0
1,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,CRUELTY BY HUSBAND OR RELATIVES,False,9.0
2,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,DOWRY DEATH,False,0.0

In [215]:
# creating a new standardized crime col and then dropping the raw col

csv2= u.standardize_crime_data(csv2, 'Crime_Head_Raw')

In [216]:
csv2.head(3)

,Year,State_UT,State_UT_Raw,Row_Type,Crime_Head_Raw,Is_Detailed_Subcategory,Count,Crime_Head_Standardized,Crime_Head_Subcategory
0,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...,False,19.0,Assault & Sexual Harassment,Assault to Outrage Modesty
1,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,CRUELTY BY HUSBAND OR RELATIVES,False,9.0,Cruelty & Dowry Offenses,Cruelty by Husband/Relatives
2,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,DOWRY DEATH,False,0.0,Cruelty & Dowry Offenses,Dowry Death

In [217]:
csv2['Crime_Head_Standardized'].unique()

array(['Assault & Sexual Harassment', 'Cruelty & Dowry Offenses',
       'Human Trafficking', 'Special & Local Laws',
       'Kidnapping & Abduction', 'Rape & Attempted Rape',
       'Total crimes against women in the state'], dtype=object)

In [218]:
csv2= csv2.drop(columns= ["Crime_Head_Raw", "Row_Type", "State_UT_Raw"])
csv2.head(3)

,Year,State_UT,Is_Detailed_Subcategory,Count,Crime_Head_Standardized,Crime_Head_Subcategory
0,2001,Andaman & Nicobar Islands,False,19.0,Assault & Sexual Harassment,Assault to Outrage Modesty
1,2001,Andaman & Nicobar Islands,False,9.0,Cruelty & Dowry Offenses,Cruelty by Husband/Relatives
2,2001,Andaman & Nicobar Islands,False,0.0,Cruelty & Dowry Offenses,Dowry Death

In [219]:
csv2= u.fill_numeric_nulls(csv2, ["Count"])

In [220]:
u.save_clean(csv2, "data/cleaned/file2.csv")

Saved | shape- (5473, 6)

All datatypes are correct and all necessary changes were made. 

**file2 or csv2 is ready for 03_Analysis.**

## c. file3.csv

In [221]:
# upload the file
csv3= u.load_data("data/cleaned/file3.csv")
csv3.head(10)

,State/UT,Cases Pending Trial from the Previous Year - ( Col. 3),Cases Sent for Trial during the year (2023) - ( Col. 4),Cases Abated by Court - ( Col. 6),Cases Withdrawn from Prosecution - ( Col. 7),Cases Compounded or Compromised - ( Col. 8),Cases Disposed off by Plea Bargaining - ( Col. 9),Cases Quashed - ( Col. 10),Cases Stayed or Sent to Record Room - ( Col. 12),Cases Convicted Out of Cases from Previous Year - ( Col. 13),Cases Convicted Out of Cases during the Year - ( Col. 14),Cases Discharged - ( Col. 16),Cases Acquitted - ( Col. 17),Conviction Rate (Col.15/Col.18)*100 - ( Col. 21),Pendency Percentage (Col.20/Col.5)*100 - ( Col. 22)
0,Andhra Pradesh,59575,21180,152,6,7340,0,33,3,466,87,142,8855,5.8,78.8
1,Arunachal Pradesh,3137,255,3,0,20,1,3,0,23,1,8,38,34.3,97.1
2,Assam,90075,11192,227,5958,6355,1,0,158,467,265,36,9066,7.4,77.9
3,Bihar,115796,17370,0,0,338,0,0,0,1114,171,65,932,56.3,98.0
4,Chhattisgarh,34270,5931,65,0,70,95,0,3,773,191,625,2777,22.1,88.6
5,Goa,1811,204,6,0,11,0,0,0,13,1,9,111,10.4,92.5
6,Gujarat,98357,6855,15,9,23,0,52,5,425,51,180,6531,6.6,93.1
7,Haryana,41260,8987,9,0,0,0,218,12,779,39,29,5159,13.6,87.6
8,Himachal Pradesh,9370,1146,3,63,25,0,111,0,135,1,5,707,16.0,90.0
9,Jharkhand,30019,6353,30,1,50,1,0,0,1215,469,29,3781,30.7,84.7

In [222]:
u.eda(csv3)

=== DataFrame ===
Shape       : 36 rows × 15 cols
Duplicates  : 0

Column Summary:
                                                                Dtype  Nulls  Null %  Uniques Flag
State/UT                                                       object      0     0.0       36
Cases Pending Trial from the Previous Year - ( Col. 3)          int64      0     0.0       36
Cases Sent for Trial during the year (2023) - ( Col. 4)         int64      0     0.0       36
Cases Abated by Court - ( Col. 6)                               int64      0     0.0       23
Cases Withdrawn from Prosecution - ( Col. 7)                    int64      0     0.0       14
Cases Compounded or Compromised - ( Col. 8)                     int64      0     0.0       24
Cases Disposed off by Plea Bargaining - ( Col. 9)               int64      0     0.0        9
Cases Quashed - ( Col. 10)                                      int64      0     0.0       21
Cases Stayed or Sent to Record Room - ( Col. 12)                int64      0     0.0       14
Cases Convicted Out of Cases from Previous Year - ( Col. 13)    int64      0     0.0       36
Cases Convicted Out of Cases during the Year - ( Col. 14)       int64      0     0.0       27
Cases Discharged - ( Col. 16)                                   int64      0     0.0       24
Cases Acquitted - ( Col. 17)                                    int64      0     0.0       35
Conviction Rate (Col.15/Col.18)*100 - ( Col. 21)              float64      0     0.0       33
Pendency Percentage (Col.20/Col.5)*100 - ( Col. 22)           float64      0     0.0       32

Numeric Stats:
                                                               min       max      mean   median
Cases Pending Trial from the Previous Year - ( Col. 3)        37.0  356330.0  60687.67  23064.5
Cases Sent for Trial during the year (2023) - ( Col. 4)       11.0   53322.0   9748.25   5168.5
Cases Abated by Court - ( Col. 6)                              0.0     889.0     63.61      9.0
Cases Withdrawn from Prosecution - ( Col. 7)                   0.0    5958.0    174.33      0.0
Cases Compounded or Compromised - ( Col. 8)                    0.0    9526.0    858.75     22.0
Cases Disposed off by Plea Bargaining - ( Col. 9)              0.0    1780.0     89.31      0.0
Cases Quashed - ( Col. 10)                                     0.0    1070.0     93.00      4.0
Cases Stayed or Sent to Record Room - ( Col. 12)               0.0     158.0     15.00      0.0
Cases Convicted Out of Cases from Previous Year - ( Col. 13)   0.0   12502.0    987.47    409.5
Cases Convicted Out of Cases during the Year - ( Col. 14)      0.0    1344.0    113.36     42.0
Cases Discharged - ( Col. 16)                                  0.0    1975.0    212.33     20.5
Cases Acquitted - ( Col. 17)                                   2.0   19005.0   3853.28   1627.5
Conviction Rate (Col.15/Col.18)*100 - ( Col. 21)               3.2      83.3     25.66     20.7
Pendency Percentage (Col.20/Col.5)*100 - ( Col. 22)           75.5      98.0     88.64     90.2

Sample:
            State/UT  Cases Pending Trial from the Previous Year - ( Col. 3)  Cases Sent for Trial during the year (2023) - ( Col. 4)  Cases Abated by Court - ( Col. 6)  Cases Withdrawn from Prosecution - ( Col. 7)  Cases Compounded or Compromised - ( Col. 8)  Cases Disposed off by Plea Bargaining - ( Col. 9)  Cases Quashed - ( Col. 10)  Cases Stayed or Sent to Record Room - ( Col. 12)  Cases Convicted Out of Cases from Previous Year - ( Col. 13)  Cases Convicted Out of Cases during the Year - ( Col. 14)  Cases Discharged - ( Col. 16)  Cases Acquitted - ( Col. 17)  Conviction Rate (Col.15/Col.18)*100 - ( Col. 21)  Pendency Percentage (Col.20/Col.5)*100 - ( Col. 22)
0     Andhra Pradesh                                                   59575                                                    21180                                152                                             6                                         7340                                                  0                          33                                                 3                                                           466                                                         87                            142                          8855                                               5.8                                                 78.8
1  Arunachal Pradesh                                                    3137                                                      255                                  3                                             0                                           20                                                  1                           3                                                 0                                                            23                                                          1                              8                            38                                              34.3                                                 97.1
2              Assam                                                   90075                                                    11192                                227                                          5958                                         6355                                                  1                           0                                               158                                                           467                                                        265                             36                          9066                                               7.4                                                 77.9

In [223]:
csv3.columns

Index(['State/UT', 'Cases Pending Trial from the Previous Year - ( Col. 3)',
       'Cases Sent for Trial during the year (2023) - ( Col. 4)',
       'Cases Abated by Court - ( Col. 6)',
       'Cases Withdrawn from Prosecution - ( Col. 7)',
       'Cases Compounded or Compromised - ( Col. 8)',
       'Cases Disposed off by Plea Bargaining - ( Col. 9)',
       'Cases Quashed - ( Col. 10)',
       'Cases Stayed or Sent to Record Room - ( Col. 12)',
       'Cases Convicted Out of Cases from Previous Year - ( Col. 13)',
       'Cases Convicted Out of Cases during the Year - ( Col. 14)',
       'Cases Discharged - ( Col. 16)', 'Cases Acquitted - ( Col. 17)',
       'Conviction Rate (Col.15/Col.18)*100 - ( Col. 21)',
       'Pendency Percentage (Col.20/Col.5)*100 - ( Col. 22)'],
      dtype='object')

In [252]:
clean_headers = {
    'Cases Pending Trial from the Previous Year - ( Col. 3)': 'Pending Cases (2022)',
    'Cases Sent for Trial during the year (2023) - ( Col. 4)': 'Cases Sent for Trial (2023)',
    'Cases Abated by Court - ( Col. 6)': 'Cases Abated',
    'Cases Withdrawn from Prosecution - ( Col. 7)': 'Cases Withdrawn',
    'Cases Compounded or Compromised - ( Col. 8)': 'Cases Compounded',
    'Cases Disposed off by Plea Bargaining - ( Col. 9)': 'Plea Bargained',
    'Cases Quashed - ( Col. 10)': 'Cases Quashed',
    'Cases Stayed or Sent to Record Room - ( Col. 12)': 'Cases Stayed/Record Room',
    'Cases Convicted Out of Cases from Previous Year - ( Col. 13)': 'Convictions (2022)',
    'Cases Convicted Out of Cases during the Year - ( Col. 14)': 'Convictions (2023)',
    'Cases Discharged - ( Col. 16)': 'Cases Discharged',
    'Cases Acquitted - ( Col. 17)': 'Cases Acquitted',
    'Conviction Rate (Col.15/Col.18)*100 - ( Col. 21)': 'Conviction Rate (%)',
    'Pendency Percentage (Col.20/Col.5)*100 - ( Col. 22)': 'Pendency Percentage (%)'
}

csv3 = csv3.rename(columns=clean_headers)

In [253]:
u.save_clean(csv3, "data/cleaned/file3.csv")

Saved | shape- (36, 15)

This file is clean.
This is the national NCRB data from the year 2023 containing info about crimes against women.

**file3 or csv3 is ready for 03_Analysis.**

## d. file4.csv

In [225]:
# upload the file
csv4= u.load_data("data/cleaned/file4.csv")
csv4.head(10)

,Cities,Population (in lakhs 2011),Rate of crime,Chargesheet rate (%),year,crime_cases
0,Ahmedabad,30.0,48.3,91.2,2020,1524
1,Bengaluru,40.6,96.7,74.2,2020,2730
2,Chennai,43.1,17.1,81.1,2020,576
3,Coimbatore,10.7,12.9,91.6,2020,97
4,Delhi City,75.8,186.9,72.4,2020,9782
5,Ghaziabad,11.0,96.5,82.0,2020,341
6,Hyderabad,37.6,83.6,71.7,2020,2390
7,Indore,10.4,174.3,75.9,2020,1346
8,Jaipur,14.5,239.3,53.0,2020,2369
9,Kanpur,13.4,157.2,75.1,2020,1056

In [226]:
u.eda(csv4)

=== DataFrame ===
Shape       : 57 rows × 6 cols
Duplicates  : 0

Column Summary:
                              Dtype  Nulls  Null %  Uniques Flag
Cities                       object      0     0.0       19
Population (in lakhs 2011)  float64      0     0.0       19
Rate of crime               float64      0     0.0       19
Chargesheet rate (%)        float64      0     0.0       19
year                          int64      0     0.0        3
crime_cases                   int64      0     0.0       57

Numeric Stats:
                               min      max     mean  median
Population (in lakhs 2011)     9.6     85.2    28.46    14.5
Rate of crime                 12.9    239.3    96.36    84.7
Chargesheet rate (%)          53.0     93.2    79.85    78.6
year                        2020.0   2022.0  2021.00  2021.0
crime_cases                   97.0  14158.0  2236.84  1452.0

Sample:
      Cities  Population (in lakhs 2011)  Rate of crime  Chargesheet rate (%)  year  crime_cases
0  Ahmedabad                        30.0           48.3                  91.2  2020         1524
1  Bengaluru                        40.6           96.7                  74.2  2020         2730
2    Chennai                        43.1           17.1                  81.1  2020          576

In [227]:
# expanding the population column to it's real number. 
csv4= u.per_lakh(csv4, "Population (in lakhs 2011)")
csv4.head(5)

,Cities,Population (in lakhs 2011),Rate of crime,Chargesheet rate (%),year,crime_cases
0,Ahmedabad,3000000.0,48.3,91.2,2020,1524
1,Bengaluru,4060000.0,96.7,74.2,2020,2730
2,Chennai,4310000.0,17.1,81.1,2020,576
3,Coimbatore,1070000.0,12.9,91.6,2020,97
4,Delhi City,7580000.0,186.9,72.4,2020,9782

In [228]:
csv4= csv4.rename(columns={"Population (in lakhs 2011)": "Population as of 2011"})
csv4= csv4.rename(columns={"Rate of crime": "Rate of crime (%)"})
csv4.head(5)

,Cities,Population as of 2011,Rate of crime (%),Chargesheet rate (%),year,crime_cases
0,Ahmedabad,3000000.0,48.3,91.2,2020,1524
1,Bengaluru,4060000.0,96.7,74.2,2020,2730
2,Chennai,4310000.0,17.1,81.1,2020,576
3,Coimbatore,1070000.0,12.9,91.6,2020,97
4,Delhi City,7580000.0,186.9,72.4,2020,9782

In [229]:
u.eda(csv4)

=== DataFrame ===
Shape       : 57 rows × 6 cols
Duplicates  : 0

Column Summary:
                         Dtype  Nulls  Null %  Uniques Flag
Cities                  object      0     0.0       19
Population as of 2011  float64      0     0.0       19
Rate of crime (%)      float64      0     0.0       19
Chargesheet rate (%)   float64      0     0.0       19
year                     int64      0     0.0        3
crime_cases              int64      0     0.0       57

Numeric Stats:
                            min        max        mean     median
Population as of 2011  960000.0  8520000.0  2846315.79  1450000.0
Rate of crime (%)          12.9      239.3       96.36       84.7
Chargesheet rate (%)       53.0       93.2       79.85       78.6
year                     2020.0     2022.0     2021.00     2021.0
crime_cases                97.0    14158.0     2236.84     1452.0

Sample:
      Cities  Population as of 2011  Rate of crime (%)  Chargesheet rate (%)  year  crime_cases
0  Ahmedabad              3000000.0               48.3                  91.2  2020         1524
1  Bengaluru              4060000.0               96.7                  74.2  2020         2730
2    Chennai              4310000.0               17.1                  81.1  2020          576

In [230]:
u.save_clean(csv4, "data/cleaned/file4.csv")

Saved | shape- (57, 6)

This file is clean. All the necessary changes were made.

**file4 or csv4 is ready for 03_Analysis.**

## e. file5.csv

In [231]:
# upload the file
csv5= u.load_data("data/cleaned/file5.csv")
csv5.head(10)

,sl_no,city,disposable_metric,person_count
0,1,Agra,PART III: A. STATUS OF PERSONS ARRESTED DURING...,1277
1,2,Ahmedabad,PART III: A. STATUS OF PERSONS ARRESTED DURING...,598
2,3,Amritsar,PART III: A. STATUS OF PERSONS ARRESTED DURING...,152
3,4,Asansol,PART III: A. STATUS OF PERSONS ARRESTED DURING...,2294
4,5,Aurangabad,PART III: A. STATUS OF PERSONS ARRESTED DURING...,1200
5,6,Bengaluru,PART III: A. STATUS OF PERSONS ARRESTED DURING...,179
6,7,Bhopal,PART III: A. STATUS OF PERSONS ARRESTED DURING...,1628
7,8,Chandigarh City,PART III: A. STATUS OF PERSONS ARRESTED DURING...,22
8,9,Chennai,PART III: A. STATUS OF PERSONS ARRESTED DURING...,150
9,10,Coimbatore,PART III: A. STATUS OF PERSONS ARRESTED DURING...,124

In [232]:
u.eda(csv5)

=== DataFrame ===
Shape       : 2703 rows × 4 cols
Duplicates  : 0

Column Summary:
                    Dtype  Nulls  Null %  Uniques Flag
sl_no               int64      0     0.0       53
city               object      0     0.0       53
disposable_metric  object      0     0.0       51
person_count        int64      0     0.0      537

Numeric Stats:
              min      max   mean  median
sl_no         1.0     53.0   27.0    27.0
person_count  0.0  96759.0  391.6     0.0

Sample:
   sl_no       city                                                                                                                                disposable_metric  person_count
0      1       Agra  PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons to whom Notice Issued during the year (but not Arrested) (Sec.41 CrPC) | Male          1277
1      2  Ahmedabad  PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons to whom Notice Issued during the year (but not Arrested) (Sec.41 CrPC) | Male           598
2      3   Amritsar  PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons to whom Notice Issued during the year (but not Arrested) (Sec.41 CrPC) | Male           152

In [233]:
csv5= csv5.rename(columns={"disposable_metric": "Crime"})
csv5.head(5)

,sl_no,city,Crime,person_count
0,1,Agra,PART III: A. STATUS OF PERSONS ARRESTED DURING...,1277
1,2,Ahmedabad,PART III: A. STATUS OF PERSONS ARRESTED DURING...,598
2,3,Amritsar,PART III: A. STATUS OF PERSONS ARRESTED DURING...,152
3,4,Asansol,PART III: A. STATUS OF PERSONS ARRESTED DURING...,2294
4,5,Aurangabad,PART III: A. STATUS OF PERSONS ARRESTED DURING...,1200

In [234]:
csv5['Crime'].unique()

array(['PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons to whom Notice Issued during the year (but not Arrested) (Sec.41 CrPC) | Male',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons to whom Notice Issued during the year (but not Arrested) (Sec.41 CrPC) | Female',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons to whom Notice Issued during the year (but not Arrested) (Sec.41 CrPC) | Transgender',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons Arrested | Persons Arrested out of Cases Registered from Previous Years | Male',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons Arrested | Persons Arrested out of Cases Registered from Previous Years | Female',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons Arrested | Persons Arrested out of Cases Registered from Previous Years | Transgender',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons Arrested | Persons Arrested in Cases Registered during the year | Male',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons Arrested | Persons Arrested in Cases Registered during the year | Female',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons Arrested | Persons Arrested in Cases Registered during the year | Transgender',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Arrested Persons Granted Bail during the year | By Police (including Persons released before trial u/s 169 Cr.PC) | Male',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Arrested Persons Granted Bail during the year | By Police (including Persons released before trial u/s 169 Cr.PC) | Female',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Arrested Persons Granted Bail during the year | By Police (including Persons released before trial u/s 169 Cr.PC) | Transgender',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Arrested Persons Granted Bail during the year | By Court | Male',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Arrested Persons Granted Bail during the year | By Court | Female',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Arrested Persons Granted Bail during the year | By Court | Transgender',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | No. of Persons Chargesheeted during the year | Persons Arrested and Chargesheeted | Male',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | No. of Persons Chargesheeted during the year | Persons Arrested and Chargesheeted | Female',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | No. of Persons Chargesheeted during the year | Persons Arrested and Chargesheeted | Transgender',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | No. of Persons Chargesheeted during the year | Persons Not Arrested but Chargesheeted | Male',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | No. of Persons Chargesheeted during the year | Persons Not Arrested but Chargesheeted | Female',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | No. of Persons Chargesheeted during the year | Persons Not Arrested but Chargesheeted | Transgender',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons against whom cases were Abated | Male',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons against whom cases were Abated | Female',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons against whom cases were Abated | Transgender',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons against whom cases were withdrawn | Male',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons against whom cases were withdrawn | Female',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons against whom cases were withdrawn | Transgender',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons against whom cases were compounded/ Compromised by Courts | Male',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons against whom cases were compounded/ Compromised by Courts | Female',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons against whom cases were compounded/ Compromised by Courts | Transgender',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons whose cases disposed of under Plea Bargaining | Male',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons whose cases disposed of under Plea Bargaining | Female',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons whose cases disposed of under Plea Bargaining | Transgender',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons whose cases were quashed by Higher Courts | Male',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons whose cases were quashed by Higher Courts | Female',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons whose cases were quashed by Higher Courts | Transgender',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons Convicted | Male',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons Convicted | Female',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons Convicted | Transgender',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons Discharged | Male',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons Discharged | Female',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons Discharged | Transgender',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons Acquitted | Male',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons Acquitted | Female',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons Acquitted | Transgender',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons in whose cases Trials were completed | Male',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons in whose cases Trials were completed | Female',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons in whose cases Trials were completed | Transgender',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose Cases Pending Trial at End of the Year | Persons in whose cases Trials were completed | Male',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose Cases Pending Trial at End of the Year | Persons in whose cases Trials were completed | Female',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose Cases Pending Trial at End of the Year | Persons in whose cases Trials were completed | Transgender'],
      dtype=object)

In [235]:
# shortening the crimes column content
csv5= u.shorten_crime_categories(csv5, "Crime")
csv5.head(5)

,sl_no,city,Crime,person_count,Arrested_Gender
0,1,Agra,Notice Issued (Sec. 41 CrPC),1277,Male
1,2,Ahmedabad,Notice Issued (Sec. 41 CrPC),598,Male
2,3,Amritsar,Notice Issued (Sec. 41 CrPC),152,Male
3,4,Asansol,Notice Issued (Sec. 41 CrPC),2294,Male
4,5,Aurangabad,Notice Issued (Sec. 41 CrPC),1200,Male

In [236]:
csv5['Crime'].unique()

array(['Notice Issued (Sec. 41 CrPC)',
       'Persons Arrested out of Cases Registered from Previous Years',
       'Persons Arrested in Cases Registered during the year',
       'By Police (including Persons released before trial u/s 169 Cr.PC)',
       'By Court', 'Persons Arrested and Chargesheeted',
       'Persons Not Arrested but Chargesheeted',
       'Persons against whom cases were Abated',
       'Persons against whom cases were withdrawn',
       'Persons against whom cases were compounded/ Compromised by Courts',
       'Persons whose cases disposed of under Plea Bargaining',
       'Persons whose cases were quashed by Higher Courts',
       'Persons Convicted', 'Persons Discharged', 'Persons Acquitted',
       'Persons in whose cases Trials were completed'], dtype=object)

In [237]:
csv5= csv5.drop(columns=['sl_no'])
csv5.head(3)

        city                         Crime  person_count Arrested_Gender
0       Agra  Notice Issued (Sec. 41 CrPC)          1277            Male
1  Ahmedabad  Notice Issued (Sec. 41 CrPC)           598            Male
2   Amritsar  Notice Issued (Sec. 41 CrPC)           152            Male

In [238]:
u.save_clean(csv5, "data/cleaned/file5.csv")

Saved | shape- (2703, 4)

All datatypes are correct and all necessary changes were made. 

**file5 or csv5 is ready for 03_Analysis.**

## f. file6.csv

In [239]:
# upload the file
csv6= u.load_data("data/cleaned/file6.csv")
csv6.head(10)

,SL,53 Metropolitan Cities,Cases Reported Under 156_3 during the year 2023,Cases Reported in Police Stations during the year 2023,Cases Reported during the year 2023
0,1.0,Agra,0,1030,1030
1,2.0,Ahmedabad,1,1359,1360
2,3.0,Amritsar,0,306,306
3,4.0,Asansol,400,295,695
4,5.0,Aurangabad,3,974,977
5,6.0,Bengaluru,68,4802,4870
6,7.0,Bhopal,0,1886,1886
7,8.0,Chandigarh City,2,369,371
8,9.0,Chennai,16,729,745
9,10.0,Coimbatore,4,240,244

In [240]:
u.eda(csv6)

=== DataFrame ===
Shape       : 53 rows × 5 cols
Duplicates  : 0

Column Summary:
                                                          Dtype  Nulls  Null %  Uniques Flag
SL                                                      float64      0     0.0       53
53 Metropolitan Cities                                   object      0     0.0       53
Cases Reported Under 156_3 during the year 2023           int64      0     0.0       26
Cases Reported in Police Stations during the year 2023    int64      0     0.0       53
Cases Reported during the year 2023                       int64      0     0.0       52

Numeric Stats:
                                                          min      max     mean  median
SL                                                        1.0     53.0    27.00    27.0
Cases Reported Under 156_3 during the year 2023           0.0   1367.0    48.57     4.0
Cases Reported in Police Stations during the year 2023  119.0  13317.0  1396.21   809.0
Cases Reported during the year 2023                     119.0  13366.0  1444.77   809.0

Sample:
    SL 53 Metropolitan Cities  Cases Reported Under 156_3 during the year 2023  Cases Reported in Police Stations during the year 2023  Cases Reported during the year 2023
0  1.0                   Agra                                                0                                                    1030                                 1030
1  2.0              Ahmedabad                                                1                                                    1359                                 1360
2  3.0               Amritsar                                                0                                                     306                                  306

In [241]:
csv6= csv6.drop(columns=['SL'])

In [242]:
csv6.head(5)

,53 Metropolitan Cities,Cases Reported Under 156_3 during the year 2023,Cases Reported in Police Stations during the year 2023,Cases Reported during the year 2023
0,Agra,0,1030,1030
1,Ahmedabad,1,1359,1360
2,Amritsar,0,306,306
3,Asansol,400,295,695
4,Aurangabad,3,974,977

In [243]:
csv6['53 Metropolitan Cities'].unique()

array(['Agra', 'Ahmedabad', 'Amritsar', 'Asansol', 'Aurangabad',
       'Bengaluru', 'Bhopal', 'Chandigarh City', 'Chennai', 'Coimbatore',
       'Delhi City', 'Dhanbad', 'Durg-Bhilainagar', 'Faridabad',
       'Ghaziabad', 'Gwalior', 'Hyderabad', 'Indore', 'Jabalpur',
       'Jaipur', 'Jamshedpur', 'Jodhpur', 'Kannur', 'Kanpur', 'Kochi',
       'Kolkata', 'Kollam', 'Kota', 'Kozhikode', 'Lucknow', 'Ludhiana',
       'Madurai', 'Malappuram', 'Meerut', 'Mumbai', 'Nagpur', 'Nasik',
       'Patna', 'Prayagraj', 'Pune', 'Raipur', 'Rajkot', 'Ranchi',
       'Srinagar', 'Surat', 'Thiruvananthapuram', 'Thrissur',
       'Tiruchirapalli', 'Vadodara', 'Varanasi', 'Vasai Virar',
       'Vijayawada', 'Vishakhapatnam'], dtype=object)

In [244]:
u.save_clean(csv6, "data/cleaned/file6.csv")

Saved | shape- (53, 4)

All datatypes are correct and all necessary changes were made. 

**file6 or csv6 is ready for 03_Analysis.**

## g. file7.csv

In [245]:
# upload the file
csv7= u.load_data("data/cleaned/file7.csv")
csv7.head(10)

,Category,State/UT,Punishment for Rape,Rape in Custody - By Police Personnel,Rape in Custody - By Public Servant,Rape in Custody - By Member of Armed Forces,Rape in Custody - By Management/Staff of Jail/Remand Home/Place of Custody,Rape in Custody - By Management/ Staff of Hospital,Other Than Custodial Rape- By Relative/Guardian/Teacher/person in position of trust,Other Than Custodial Rape- On Pregnant Women,...,Other Than Custodial Rape- Endanger life of Women after Rape,Other Than Custodial Rape - Repeated Rape on same women,Punishment upto 20 years extended to life for Rape (Below 16 Yrs),Punishment for causing Death,By Separated husband,Rape/Gang Rape of Girl Below 16 Yrs (Imprisonment for life till death),By Person in Authority,Gang Rape,Rape/Gang Rape of Girl Below 12 Yrs (Imprisonment for life till death),Punishment for Repeat offenders
0,State,Andhra Pradesh,758,0,0,1,0,0,17,0,...,0,98,15,0,0,10,1,9,2,0
1,State,Arunachal Pradesh,46,0,0,0,0,0,4,0,...,0,2,0,0,1,0,0,4,0,0
2,State,Assam,1599,0,0,0,11,0,31,0,...,0,0,0,1,1,1,30,25,0,0
3,State,Bihar,700,0,0,0,0,0,16,0,...,0,0,0,0,0,0,0,14,0,0
4,State,Chhattisgarh,546,1,0,0,0,0,267,2,...,3,31,0,0,0,3,0,15,0,0
5,State,Goa,54,0,0,0,0,1,6,0,...,0,1,1,0,0,0,0,2,0,0
6,State,Gujarat,429,0,0,0,0,0,14,1,...,2,62,0,0,0,0,0,14,0,0
7,State,Haryana,900,0,1,0,0,1,11,4,...,0,308,0,2,4,0,1,159,0,49
8,State,Himachal Pradesh,302,0,0,0,0,0,26,0,...,0,1,2,0,0,1,0,4,0,0
9,State,Jammu & Kashmir,177,0,0,0,0,0,46,0,...,0,0,0,0,0,0,0,0,0,0

In [246]:
u.eda(csv7)

=== DataFrame ===
Shape       : 36 rows × 24 cols
Duplicates  : 0

Column Summary:
                                                                                       Dtype  Nulls  Null %  Uniques Flag
Category                                                                              object      0     0.0        2
State/UT                                                                              object      0     0.0       36
Punishment for Rape                                                                    int64      0     0.0       32
Rape in Custody - By Police Personnel                                                  int64      0     0.0        3
Rape in Custody - By Public Servant                                                    int64      0     0.0        3
Rape in Custody  - By Member of Armed Forces                                           int64      0     0.0        2
Rape in Custody - By Management/Staff of Jail/Remand Home/Place of Custody             int64      0     0.0        4
Rape in Custody  - By Management/ Staff of Hospital                                    int64      0     0.0        2
Other Than Custodial Rape- By Relative/Guardian/Teacher/person in position of trust    int64      0     0.0       23
Other Than Custodial Rape- On Pregnant Women                                           int64      0     0.0        7
Other Than Custodial Rape - On Women Below 16 years of age                             int64      0     0.0       18
Other Than Custodial Rape - On Women Incapable of giving Consent                       int64      0     0.0       10
Other Than Custodial Rape - By Persons in Control or Dominance over women              int64      0     0.0        8
Other Than Custodial Rape - On Women with Mental or Physical disability                int64      0     0.0       11
Other Than Custodial Rape- Endanger life of Women after Rape                           int64      0     0.0        7
Other Than Custodial Rape - Repeated Rape on same women                                int64      0     0.0       20
Punishment upto 20 years extended to life for Rape (Below 16 Yrs)                      int64      0     0.0       14
Punishment for causing Death                                                           int64      0     0.0        5
By Separated husband                                                                   int64      0     0.0        8
Rape/Gang Rape of Girl Below 16 Yrs (Imprisonment for life till death)                 int64      0     0.0       11
By Person in Authority                                                                 int64      0     0.0        5
Gang Rape                                                                              int64      0     0.0       21
Rape/Gang Rape of Girl Below 12 Yrs (Imprisonment for life till death)                 int64      0     0.0        6
Punishment for Repeat offenders                                                        int64      0     0.0        4

Numeric Stats:
                                                                                      min     max    mean  median
Punishment for Rape                                                                   0.0  3826.0  631.22   381.5
Rape in Custody - By Police Personnel                                                 0.0     3.0    0.14     0.0
Rape in Custody - By Public Servant                                                   0.0    10.0    0.36     0.0
Rape in Custody  - By Member of Armed Forces                                          0.0     1.0    0.03     0.0
Rape in Custody - By Management/Staff of Jail/Remand Home/Place of Custody            0.0    12.0    0.67     0.0
Rape in Custody  - By Management/ Staff of Hospital                                   0.0     1.0    0.11     0.0
Other Than Custodial Rape- By Relative/Guardian/Teacher/person in position of trust   0.0   481.0   55.53     8.0
Other Than Custodial Rape- On Pregnant Women                                          0.0    11.0    0.97     0.0
Other Than Custodial Rape - On Women Below 16 years of age                            0.0   203.0   21.94     0.0
Other Than Custodial Rape - On Women Incapable of giving Consent                      0.0   216.0   10.92     0.0
Other Than Custodial Rape - By Persons in Control or Dominance over women             0.0   118.0    5.06     0.0
Other Than Custodial Rape - On Women with Mental or Physical disability               0.0    29.0    3.22     0.0
Other Than Custodial Rape- Endanger life of Women after Rape                          0.0    11.0    0.94     0.0
Other Than Custodial Rape - Repeated Rape on same women                               0.0   748.0   65.92     2.0
Punishment upto 20 years extended to life for Rape (Below 16 Yrs)                     0.0    37.0    5.03     0.0
Punishment for causing Death                                                          0.0    11.0    0.75     0.0
By Separated husband                                                                  0.0     7.0    1.03     0.0
Rape/Gang Rape of Girl Below 16 Yrs (Imprisonment for life till death)                0.0    71.0    4.72     0.0
By Person in Authority                                                                0.0    30.0    1.22     0.0
Gang Rape                                                                             0.0   902.0   53.64     7.0
Rape/Gang Rape of Girl Below 12 Yrs (Imprisonment for life till death)                0.0    31.0    1.31     0.0
Punishment for Repeat offenders                                                       0.0    52.0    2.89     0.0

Sample:
  Category           State/UT  Punishment for Rape  Rape in Custody - By Police Personnel  Rape in Custody - By Public Servant   Rape in Custody  - By Member of Armed Forces   Rape in Custody - By Management/Staff of Jail/Remand Home/Place of Custody   Rape in Custody  - By Management/ Staff of Hospital  Other Than Custodial Rape- By Relative/Guardian/Teacher/person in position of trust   Other Than Custodial Rape- On Pregnant Women   Other Than Custodial Rape - On Women Below 16 years of age   Other Than Custodial Rape - On Women Incapable of giving Consent   Other Than Custodial Rape - By Persons in Control or Dominance over women  Other Than Custodial Rape - On Women with Mental or Physical disability  Other Than Custodial Rape- Endanger life of Women after Rape   Other Than Custodial Rape - Repeated Rape on same women  Punishment upto 20 years extended to life for Rape (Below 16 Yrs)   Punishment for causing Death  By Separated husband   Rape/Gang Rape of Girl Below 16 Yrs (Imprisonment for life till death)   By Person in Authority   Gang Rape  Rape/Gang Rape of Girl Below 12 Yrs (Imprisonment for life till death)   Punishment for Repeat offenders
0    State     Andhra Pradesh                  758                                      0                                     0                                              1                                                                            0                                                    0                                                                                    17                                              0                                                          101                                                                 12                                                                          2                                                                        8                                                              0                                                       98                                                                  15                             0                      0                                                                       10                        1          9                                                                        2                                 0
1    State  Arunachal Pradesh                   46                                      0                                     0                                              0                                                                            0                                                    0                                                                                     4                                              0                                                            4                                                                  0                                                                          0                                                                        2                                                              0                                                        2                                                                   0                             0                      1                                                                        0                        0          4                                                                        0                                 0
2    State              Assam                 1599                                      0                                     0                                              0                                                                           11                                                    0                                                                                    31                                              0                                                            1                                                                 21                                                                         36                                                                        1                                                              0                                                        0                                                                   0                             1                      1                                                                        1                       30         25                                                                        0                                 0

In [247]:
# converting it from wide to long format and optimize the categories.
csv7= u.optimize_crime_df(csv7)
csv7.head(10)

,Category,State/UT,Offense_Category,Offense_Subcategory,Incidents
0,State,Andhra Pradesh,Penalties & Legal Provisions,General Offences (Section Penalties),758
1,State,Arunachal Pradesh,Penalties & Legal Provisions,General Offences (Section Penalties),46
2,State,Assam,Penalties & Legal Provisions,General Offences (Section Penalties),1599
3,State,Bihar,Penalties & Legal Provisions,General Offences (Section Penalties),700
4,State,Chhattisgarh,Penalties & Legal Provisions,General Offences (Section Penalties),546
5,State,Goa,Penalties & Legal Provisions,General Offences (Section Penalties),54
6,State,Gujarat,Penalties & Legal Provisions,General Offences (Section Penalties),429
7,State,Haryana,Penalties & Legal Provisions,General Offences (Section Penalties),900
8,State,Himachal Pradesh,Penalties & Legal Provisions,General Offences (Section Penalties),302
9,State,Jammu & Kashmir,Penalties & Legal Provisions,General Offences (Section Penalties),177

In [248]:
u.eda(csv7)

=== DataFrame ===
Shape       : 792 rows × 5 cols
Duplicates  : 0

Column Summary:
                      Dtype  Nulls  Null %  Uniques Flag
Category             object      0     0.0        2
State/UT             object      0     0.0       36
Offense_Category     object      0     0.0        4
Offense_Subcategory  object      0     0.0       22
Incidents             int16      0     0.0       93

Numeric Stats:
           min     max   mean  median
Incidents  0.0  3826.0  39.44     0.0

Sample:
  Category           State/UT              Offense_Category                   Offense_Subcategory  Incidents
0    State     Andhra Pradesh  Penalties & Legal Provisions  General Offences (Section Penalties)        758
1    State  Arunachal Pradesh  Penalties & Legal Provisions  General Offences (Section Penalties)         46
2    State              Assam  Penalties & Legal Provisions  General Offences (Section Penalties)       1599

In [249]:
csv7['Offense_Category'].unique()

array(['Penalties & Legal Provisions', 'Custodial', 'Non-Custodial',
       'Aggravated & Gang'], dtype=object)

In [250]:
csv7['Offense_Subcategory'].unique()

array(['General Offences (Section Penalties)', 'Police Personnel',
       'Public Servant', 'Member of Armed Forces',
       'Management/Staff of Jail/Remand Home/Place of Custody',
       'Management/ Staff of Hospital',
       'Relative/Guardian/Teacher/person in position of trust',
       'Pregnant Women', 'Women Below 16 years of age',
       'Women Incapable of giving Consent',
       'Persons in Control or Dominance over women',
       'Women with Mental or Physical disability',
       'Endanger life of Women', 'Repeated on same women',
       'Punishment upto 20 years extended to life (Below 16 Yrs)',
       'Punishment for causing Death', 'Separated husband',
       'Girl Below 16 Yrs (Imprisonment for life till death)',
       'Person in Authority', 'Gang Incidents',
       'Girl Below 12 Yrs (Imprisonment for life till death)',
       'Punishment for Repeat offenders'], dtype=object)

In [251]:
u.save_clean(csv7, "data/cleaned/file7.csv")

Saved | shape- (792, 5)

All datatypes are correct and all necessary changes were made. 

**file7 or csv7 is ready for 03_Analysis.**