# Thread 2: Gender Injustice

### This thread looks at the crimes against women in the past decade and concludes important pointers from it. For ex- how the rate of crime against women is affected each year, whether criminals are convicted, etc.

## Cleaning

# 01. Import libraries

In [284]:
import pandas as pd
import sys
sys.path.append("..")

import utility as u

import importlib
importlib.reload(u)

# 02. Cleaning each file before using it for analysis

    NOTE

--> All the files will be loaded from `data/cleaned` (output from 01_EDA)

## a. file1.csv

In [285]:
# load the file
csv1= u.load_data("data/cleaned/file1.csv")

In [286]:
csv1.head(5)

                                          CRIME HEAD  year  cases
0                                               Rape  2001  16075
1          Kidnapping and Abduction of Women & Girls  2001  14645
2                                       Dowry Deaths  2001   6851
3  Assault on women with intent to outrage her mo...  2001  34124
4                     Insult to the modesty of Women  2001   9746

In [287]:
# checking the datatypes of all columns
u.eda(csv1)

=== DataFrame ===
Shape       : 242 rows × 3 cols
Duplicates  : 0

Column Summary:
             Dtype  Nulls  Null %  Uniques Flag
CRIME HEAD  object      0     0.0       11
year         int64      0     0.0       22
cases        int64      0     0.0      237

Numeric Stats:
          min       max      mean   median
year   2001.0    2022.0   2011.50   2011.5
cases     1.0  370616.0  45496.25  10277.5

Sample:
                                  CRIME HEAD  year  cases
0                                       Rape  2001  16075
1  Kidnapping and Abduction of Women & Girls  2001  14645
2                               Dowry Deaths  2001   6851

All datatypes are correct and need no changes. 

**file1 or csv1 is ready for 03_Analysis.**

## b. file2.csv

In [288]:
# load the file
csv2= u.load_data("data/cleaned/file2.csv")
csv2.head(5)

,Year,State_UT,State_UT_Raw,Row_Type,Crime_Head_Standardized,Crime_Head_Raw,Is_Detailed_Subcategory,Count
0,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Assault on Women with Intent to Outrage Modesty,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...,False,19.0
1,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Cruelty by Husband or Relatives,CRUELTY BY HUSBAND OR RELATIVES,False,9.0
2,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Dowry Deaths,DOWRY DEATH,False,0.0
3,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Immoral Traffic (Prevention) Act,IMMORAL TRAFFIC(PREVENTION)ACT,False,0.0
4,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Indecent Representation of Women (Prevention) Act,INDECENT REPRESENTATION OF WOMEN(PREVENTION)ACT,False,0.0

In [289]:
# checking the datatypes of all columns
u.eda(csv2)

=== DataFrame ===
Shape       : 5473 rows × 8 cols
Duplicates  : 0

Column Summary:
                           Dtype  Nulls  Null %  Uniques Flag
Year                       int64      0    0.00       25
State_UT                  object      0    0.00       38
State_UT_Raw              object      0    0.00       39
Row_Type                  object      0    0.00        1
Crime_Head_Standardized   object    900   16.44       15
Crime_Head_Raw            object      0    0.00       57
Is_Detailed_Subcategory     bool      0    0.00        2
Count                    float64    108    1.97     1581

Numeric Stats:
          min      max     mean  median
Year   2001.0   2025.0  2009.76  2010.0
Count     0.0  66381.0  1151.52    33.0

Sample:
   Year                   State_UT State_UT_Raw  Row_Type                          Crime_Head_Standardized                                       Crime_Head_Raw  Is_Detailed_Subcategory  Count
0  2001  Andaman & Nicobar Islands  A&N Islands  State/UT  Assault on Women with Intent to Outrage Modesty  ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY                    False   19.0
1  2001  Andaman & Nicobar Islands  A&N Islands  State/UT                  Cruelty by Husband or Relatives                      CRUELTY BY HUSBAND OR RELATIVES                    False    9.0
2  2001  Andaman & Nicobar Islands  A&N Islands  State/UT                                     Dowry Deaths                                          DOWRY DEATH                    False    0.0

In [290]:
csv2['Crime_Head_Standardized'].unique()

array(['Assault on Women with Intent to Outrage Modesty',
       'Cruelty by Husband or Relatives', 'Dowry Deaths',
       'Immoral Traffic (Prevention) Act',
       'Indecent Representation of Women (Prevention) Act',
       'Insult to Modesty of Women', 'Kidnapping & Abduction of Women',
       'Rape', 'Commission of Sati (Prevention) Act',
       'Dowry Prohibition Act',
       'Importation of Girls from Foreign Country', nan,
       'Protection of Women from Domestic Violence Act',
       'Attempt to Commit Rape', 'Abetment of Suicide of Women',
       'Total Crimes against Women'], dtype=object)

In [291]:
# creating a standardized crime column to replace raw one
# removing existing standardized col as it contains a large amount of nulls which will hinder dataset integrity.

csv2 = csv2.drop(columns=['Crime_Head_Standardized'])
csv2.head(3)

,Year,State_UT,State_UT_Raw,Row_Type,Crime_Head_Raw,Is_Detailed_Subcategory,Count
0,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...,False,19.0
1,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,CRUELTY BY HUSBAND OR RELATIVES,False,9.0
2,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,DOWRY DEATH,False,0.0

In [292]:
# creating a new standardized crime col and then dropping the raw col

csv2= u.standardize_crime_data(csv2, 'Crime_Head_Raw')

In [293]:
csv2.head(3)

,Year,State_UT,State_UT_Raw,Row_Type,Crime_Head_Raw,Is_Detailed_Subcategory,Count,Crime_Head_Standardized,Crime_Head_Subcategory
0,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...,False,19.0,Assault & Sexual Harassment,Assault to Outrage Modesty
1,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,CRUELTY BY HUSBAND OR RELATIVES,False,9.0,Cruelty & Dowry Offenses,Cruelty by Husband/Relatives
2,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,DOWRY DEATH,False,0.0,Cruelty & Dowry Offenses,Dowry Death

In [294]:
csv2['Crime_Head_Standardized'].unique()

array(['Assault & Sexual Harassment', 'Cruelty & Dowry Offenses',
       'Human Trafficking', 'Special & Local Laws',
       'Kidnapping & Abduction', 'Rape & Attempted Rape',
       'Total crimes against women in the state'], dtype=object)

In [295]:
csv2= csv2.drop(columns= ["Crime_Head_Raw", "Row_Type", "State_UT_Raw"])
csv2.head(3)

,Year,State_UT,Is_Detailed_Subcategory,Count,Crime_Head_Standardized,Crime_Head_Subcategory
0,2001,Andaman & Nicobar Islands,False,19.0,Assault & Sexual Harassment,Assault to Outrage Modesty
1,2001,Andaman & Nicobar Islands,False,9.0,Cruelty & Dowry Offenses,Cruelty by Husband/Relatives
2,2001,Andaman & Nicobar Islands,False,0.0,Cruelty & Dowry Offenses,Dowry Death

In [296]:
csv2= u.fill_numeric_nulls(csv2, ["Count"])

In [297]:
u.save_clean(csv2, "data/cleaned/file2.csv")

Saved | shape- (5473, 6)

All datatypes are correct and all necessary changes were made. 

**file2 or csv2 is ready for 03_Analysis.**

## c. file3.csv

In [298]:
# upload the file
csv3= u.load_data("data/cleaned/file3.csv")
csv3.head(10)

,State/UT,Cases Pending Trial from the Previous Year - ( Col. 3),Cases Sent for Trial during the year (2023) - ( Col. 4),Total Cases for Trial (Col.3+Col.4) - ( Col. 5),Cases Convicted (Col.13+Col.14) - ( Col. 15),Cases Discharged - ( Col. 16),Cases Acquitted - ( Col. 17),Cases in which Trials were Completed (Col.15+Col.16+ Col.17) - ( Col. 18),Cases Pending Trial at End of the Year (Col.5-Col.19) - ( Col. 20),Conviction Rate (Col.15/Col.18)*100 - ( Col. 21),Pendency Percentage (Col.20/Col.5)*100 - ( Col. 22)
0,Andhra Pradesh,59575,21180,80755,553,142,8855,9550,63674,5.8,78.8
1,Arunachal Pradesh,3137,255,3392,24,8,38,70,3295,34.3,97.1
2,Assam,90075,11192,101267,732,36,9066,9834,78892,7.4,77.9
3,Bihar,115796,17370,133166,1285,65,932,2282,130546,56.3,98.0
4,Chhattisgarh,34270,5931,40201,964,625,2777,4366,35605,22.1,88.6
5,Goa,1811,204,2015,14,9,111,134,1864,10.4,92.5
6,Gujarat,98357,6855,105212,476,180,6531,7187,97926,6.6,93.1
7,Haryana,41260,8987,50247,818,29,5159,6006,44014,13.6,87.6
8,Himachal Pradesh,9370,1146,10516,136,5,707,848,9466,16.0,90.0
9,Jharkhand,30019,6353,36372,1684,29,3781,5494,30796,30.7,84.7

In [299]:
u.eda(csv3)

=== DataFrame ===
Shape       : 36 rows × 11 cols
Duplicates  : 0

Column Summary:
                                                                             Dtype  Nulls  Null %  Uniques Flag
State/UT                                                                    object      0     0.0       36
Cases Pending Trial from the Previous Year - ( Col. 3)                       int64      0     0.0       36
Cases Sent for Trial during the year (2023) - ( Col. 4)                      int64      0     0.0       36
Total Cases for Trial (Col.3+Col.4) - ( Col. 5)                              int64      0     0.0       36
Cases Convicted (Col.13+Col.14) - ( Col. 15)                                 int64      0     0.0       35
Cases Discharged - ( Col. 16)                                                int64      0     0.0       24
Cases Acquitted - ( Col. 17)                                                 int64      0     0.0       35
Cases in which Trials were Completed (Col.15+Col.16+ Col.17) - ( Col. 18)    int64      0     0.0       36
Cases Pending Trial at End of the Year (Col.5-Col.19) - ( Col. 20)           int64      0     0.0       36
Conviction Rate (Col.15/Col.18)*100 - ( Col. 21)                           float64      0     0.0       33
Pendency Percentage (Col.20/Col.5)*100 - ( Col. 22)                        float64      0     0.0       32

Numeric Stats:
                                                                            min       max      mean   median
Cases Pending Trial from the Previous Year - ( Col. 3)                     37.0  356330.0  60687.67  23064.5
Cases Sent for Trial during the year (2023) - ( Col. 4)                    11.0   53322.0   9748.25   5168.5
Total Cases for Trial (Col.3+Col.4) - ( Col. 5)                            48.0  388557.0  70435.92  28160.5
Cases Convicted (Col.13+Col.14) - ( Col. 15)                                2.0   13846.0   1100.83    452.0
Cases Discharged - ( Col. 16)                                               0.0    1975.0    212.33     20.5
Cases Acquitted - ( Col. 17)                                                2.0   19005.0   3853.28   1627.5
Cases in which Trials were Completed (Col.15+Col.16+ Col.17) - ( Col. 18)   6.0   21425.0   5166.44   2583.0
Cases Pending Trial at End of the Year (Col.5-Col.19) - ( Col. 20)         41.0  368364.0  63990.47  24694.0
Conviction Rate (Col.15/Col.18)*100 - ( Col. 21)                            3.2      83.3     25.66     20.7
Pendency Percentage (Col.20/Col.5)*100 - ( Col. 22)                        75.5      98.0     88.64     90.2

Sample:
            State/UT  Cases Pending Trial from the Previous Year - ( Col. 3)  Cases Sent for Trial during the year (2023) - ( Col. 4)  Total Cases for Trial (Col.3+Col.4) - ( Col. 5)  Cases Convicted (Col.13+Col.14) - ( Col. 15)  Cases Discharged - ( Col. 16)  Cases Acquitted - ( Col. 17)  Cases in which Trials were Completed (Col.15+Col.16+ Col.17) - ( Col. 18)  Cases Pending Trial at End of the Year (Col.5-Col.19) - ( Col. 20)  Conviction Rate (Col.15/Col.18)*100 - ( Col. 21)  Pendency Percentage (Col.20/Col.5)*100 - ( Col. 22)
0     Andhra Pradesh                                                   59575                                                    21180                                            80755                                           553                            142                          8855                                                                       9550                                                               63674                                               5.8                                                 78.8
1  Arunachal Pradesh                                                    3137                                                      255                                             3392                                            24                              8                            38                                                                         70                                                                3295                                              34.3                                                 97.1
2              Assam                                                   90075                                                    11192                                           101267                                           732                             36                          9066                                                                       9834                                                               78892                                               7.4                                                 77.9

This file is clean.
This is the national NCRB data from the year 2023 containing info about crimes against women.

**file3 or csv3 is ready for 03_Analysis.**

## d. file4.csv

In [300]:
# upload the file
csv4= u.load_data("data/cleaned/file4.csv")
csv4.head(10)

,Cities,Population (in lakhs 2011),Rate of crime,Chargesheet rate (%),year,crime_cases
0,Ahmedabad,30.0,48.3,91.2,2020,1524
1,Bengaluru,40.6,96.7,74.2,2020,2730
2,Chennai,43.1,17.1,81.1,2020,576
3,Coimbatore,10.7,12.9,91.6,2020,97
4,Delhi City,75.8,186.9,72.4,2020,9782
5,Ghaziabad,11.0,96.5,82.0,2020,341
6,Hyderabad,37.6,83.6,71.7,2020,2390
7,Indore,10.4,174.3,75.9,2020,1346
8,Jaipur,14.5,239.3,53.0,2020,2369
9,Kanpur,13.4,157.2,75.1,2020,1056

In [301]:
u.eda(csv4)

=== DataFrame ===
Shape       : 57 rows × 6 cols
Duplicates  : 0

Column Summary:
                              Dtype  Nulls  Null %  Uniques Flag
Cities                       object      0     0.0       19
Population (in lakhs 2011)  float64      0     0.0       19
Rate of crime               float64      0     0.0       19
Chargesheet rate (%)        float64      0     0.0       19
year                          int64      0     0.0        3
crime_cases                   int64      0     0.0       57

Numeric Stats:
                               min      max     mean  median
Population (in lakhs 2011)     9.6     85.2    28.46    14.5
Rate of crime                 12.9    239.3    96.36    84.7
Chargesheet rate (%)          53.0     93.2    79.85    78.6
year                        2020.0   2022.0  2021.00  2021.0
crime_cases                   97.0  14158.0  2236.84  1452.0

Sample:
      Cities  Population (in lakhs 2011)  Rate of crime  Chargesheet rate (%)  year  crime_cases
0  Ahmedabad                        30.0           48.3                  91.2  2020         1524
1  Bengaluru                        40.6           96.7                  74.2  2020         2730
2    Chennai                        43.1           17.1                  81.1  2020          576

In [302]:
# expanding the population column to it's real number. 
csv4= u.per_lakh(csv4, "Population (in lakhs 2011)")
csv4.head(5)

,Cities,Population (in lakhs 2011),Rate of crime,Chargesheet rate (%),year,crime_cases
0,Ahmedabad,3000000.0,48.3,91.2,2020,1524
1,Bengaluru,4060000.0,96.7,74.2,2020,2730
2,Chennai,4310000.0,17.1,81.1,2020,576
3,Coimbatore,1070000.0,12.9,91.6,2020,97
4,Delhi City,7580000.0,186.9,72.4,2020,9782

In [303]:
csv4= csv4.rename(columns={"Population (in lakhs 2011)": "Population as of 2011"})
csv4= csv4.rename(columns={"Rate of crime": "Rate of crime (%)"})
csv4.head(5)

,Cities,Population as of 2011,Rate of crime (%),Chargesheet rate (%),year,crime_cases
0,Ahmedabad,3000000.0,48.3,91.2,2020,1524
1,Bengaluru,4060000.0,96.7,74.2,2020,2730
2,Chennai,4310000.0,17.1,81.1,2020,576
3,Coimbatore,1070000.0,12.9,91.6,2020,97
4,Delhi City,7580000.0,186.9,72.4,2020,9782

In [304]:
u.eda(csv4)

=== DataFrame ===
Shape       : 57 rows × 6 cols
Duplicates  : 0

Column Summary:
                         Dtype  Nulls  Null %  Uniques Flag
Cities                  object      0     0.0       19
Population as of 2011  float64      0     0.0       19
Rate of crime (%)      float64      0     0.0       19
Chargesheet rate (%)   float64      0     0.0       19
year                     int64      0     0.0        3
crime_cases              int64      0     0.0       57

Numeric Stats:
                            min        max        mean     median
Population as of 2011  960000.0  8520000.0  2846315.79  1450000.0
Rate of crime (%)          12.9      239.3       96.36       84.7
Chargesheet rate (%)       53.0       93.2       79.85       78.6
year                     2020.0     2022.0     2021.00     2021.0
crime_cases                97.0    14158.0     2236.84     1452.0

Sample:
      Cities  Population as of 2011  Rate of crime (%)  Chargesheet rate (%)  year  crime_cases
0  Ahmedabad              3000000.0               48.3                  91.2  2020         1524
1  Bengaluru              4060000.0               96.7                  74.2  2020         2730
2    Chennai              4310000.0               17.1                  81.1  2020          576

In [305]:
u.save_clean(csv4, "data/cleaned/file4.csv")

Saved | shape- (57, 6)

This file is clean. All the necessary changes were made.

**file4 or csv4 is ready for 03_Analysis.**

## e. file5.csv

In [306]:
# upload the file
csv5= u.load_data("data/cleaned/file5.csv")
csv5.head(10)

,sl_no,city,disposable_metric,person_count
0,1,Agra,PART III: A. STATUS OF PERSONS ARRESTED DURING...,1277
1,2,Ahmedabad,PART III: A. STATUS OF PERSONS ARRESTED DURING...,598
2,3,Amritsar,PART III: A. STATUS OF PERSONS ARRESTED DURING...,152
3,4,Asansol,PART III: A. STATUS OF PERSONS ARRESTED DURING...,2294
4,5,Aurangabad,PART III: A. STATUS OF PERSONS ARRESTED DURING...,1200
5,6,Bengaluru,PART III: A. STATUS OF PERSONS ARRESTED DURING...,179
6,7,Bhopal,PART III: A. STATUS OF PERSONS ARRESTED DURING...,1628
7,8,Chandigarh City,PART III: A. STATUS OF PERSONS ARRESTED DURING...,22
8,9,Chennai,PART III: A. STATUS OF PERSONS ARRESTED DURING...,150
9,10,Coimbatore,PART III: A. STATUS OF PERSONS ARRESTED DURING...,124

In [307]:
u.eda(csv5)

=== DataFrame ===
Shape       : 2703 rows × 4 cols
Duplicates  : 0

Column Summary:
                    Dtype  Nulls  Null %  Uniques Flag
sl_no               int64      0     0.0       53
city               object      0     0.0       53
disposable_metric  object      0     0.0       51
person_count        int64      0     0.0      537

Numeric Stats:
              min      max   mean  median
sl_no         1.0     53.0   27.0    27.0
person_count  0.0  96759.0  391.6     0.0

Sample:
   sl_no       city                                                                                                                                disposable_metric  person_count
0      1       Agra  PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons to whom Notice Issued during the year (but not Arrested) (Sec.41 CrPC) | Male          1277
1      2  Ahmedabad  PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons to whom Notice Issued during the year (but not Arrested) (Sec.41 CrPC) | Male           598
2      3   Amritsar  PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons to whom Notice Issued during the year (but not Arrested) (Sec.41 CrPC) | Male           152

In [308]:
csv5= csv5.rename(columns={"disposable_metric": "Crime"})
csv5.head(5)

,sl_no,city,Crime,person_count
0,1,Agra,PART III: A. STATUS OF PERSONS ARRESTED DURING...,1277
1,2,Ahmedabad,PART III: A. STATUS OF PERSONS ARRESTED DURING...,598
2,3,Amritsar,PART III: A. STATUS OF PERSONS ARRESTED DURING...,152
3,4,Asansol,PART III: A. STATUS OF PERSONS ARRESTED DURING...,2294
4,5,Aurangabad,PART III: A. STATUS OF PERSONS ARRESTED DURING...,1200

In [309]:
csv5['Crime'].unique()

array(['PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons to whom Notice Issued during the year (but not Arrested) (Sec.41 CrPC) | Male',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons to whom Notice Issued during the year (but not Arrested) (Sec.41 CrPC) | Female',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons to whom Notice Issued during the year (but not Arrested) (Sec.41 CrPC) | Transgender',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons Arrested | Persons Arrested out of Cases Registered from Previous Years | Male',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons Arrested | Persons Arrested out of Cases Registered from Previous Years | Female',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons Arrested | Persons Arrested out of Cases Registered from Previous Years | Transgender',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons Arrested | Persons Arrested in Cases Registered during the year | Male',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons Arrested | Persons Arrested in Cases Registered during the year | Female',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Persons Arrested | Persons Arrested in Cases Registered during the year | Transgender',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Arrested Persons Granted Bail during the year | By Police (including Persons released before trial u/s 169 Cr.PC) | Male',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Arrested Persons Granted Bail during the year | By Police (including Persons released before trial u/s 169 Cr.PC) | Female',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Arrested Persons Granted Bail during the year | By Police (including Persons released before trial u/s 169 Cr.PC) | Transgender',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Arrested Persons Granted Bail during the year | By Court | Male',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Arrested Persons Granted Bail during the year | By Court | Female',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | Arrested Persons Granted Bail during the year | By Court | Transgender',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | No. of Persons Chargesheeted during the year | Persons Arrested and Chargesheeted | Male',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | No. of Persons Chargesheeted during the year | Persons Arrested and Chargesheeted | Female',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | No. of Persons Chargesheeted during the year | Persons Arrested and Chargesheeted | Transgender',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | No. of Persons Chargesheeted during the year | Persons Not Arrested but Chargesheeted | Male',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | No. of Persons Chargesheeted during the year | Persons Not Arrested but Chargesheeted | Female',
       'PART III: A. STATUS OF PERSONS ARRESTED DURING THE YEAR | No. of Persons Chargesheeted during the year | Persons Not Arrested but Chargesheeted | Transgender',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons against whom cases were Abated | Male',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons against whom cases were Abated | Female',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons against whom cases were Abated | Transgender',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons against whom cases were withdrawn | Male',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons against whom cases were withdrawn | Female',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons against whom cases were withdrawn | Transgender',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons against whom cases were compounded/ Compromised by Courts | Male',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons against whom cases were compounded/ Compromised by Courts | Female',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons against whom cases were compounded/ Compromised by Courts | Transgender',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons whose cases disposed of under Plea Bargaining | Male',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons whose cases disposed of under Plea Bargaining | Female',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons whose cases disposed of under Plea Bargaining | Transgender',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons whose cases were quashed by Higher Courts | Male',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons whose cases were quashed by Higher Courts | Female',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases disposed off Without Trial | Persons whose cases were quashed by Higher Courts | Transgender',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons Convicted | Male',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons Convicted | Female',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons Convicted | Transgender',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons Discharged | Male',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons Discharged | Female',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons Discharged | Transgender',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons Acquitted | Male',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons Acquitted | Female',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons Acquitted | Transgender',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons in whose cases Trials were completed | Male',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons in whose cases Trials were completed | Female',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose cases were Tried by Courts | Persons in whose cases Trials were completed | Transgender',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose Cases Pending Trial at End of the Year | Persons in whose cases Trials were completed | Male',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose Cases Pending Trial at End of the Year | Persons in whose cases Trials were completed | Female',
       'PART III: B. TRIAL OF PERSONS (including Pending Trial from previous years) | Persons whose Cases Pending Trial at End of the Year | Persons in whose cases Trials were completed | Transgender'],
      dtype=object)

In [310]:
# shortening the crimes column content
csv5= u.shorten_crime_categories(csv5, "Crime")
csv5.head(5)

,sl_no,city,Crime,person_count,Arrested_Gender
0,1,Agra,Notice Issued (Sec. 41 CrPC),1277,Male
1,2,Ahmedabad,Notice Issued (Sec. 41 CrPC),598,Male
2,3,Amritsar,Notice Issued (Sec. 41 CrPC),152,Male
3,4,Asansol,Notice Issued (Sec. 41 CrPC),2294,Male
4,5,Aurangabad,Notice Issued (Sec. 41 CrPC),1200,Male

In [311]:
csv5['Crime'].unique()

array(['Notice Issued (Sec. 41 CrPC)',
       'Persons Arrested out of Cases Registered from Previous Years',
       'Persons Arrested in Cases Registered during the year',
       'By Police (including Persons released before trial u/s 169 Cr.PC)',
       'By Court', 'Persons Arrested and Chargesheeted',
       'Persons Not Arrested but Chargesheeted',
       'Persons against whom cases were Abated',
       'Persons against whom cases were withdrawn',
       'Persons against whom cases were compounded/ Compromised by Courts',
       'Persons whose cases disposed of under Plea Bargaining',
       'Persons whose cases were quashed by Higher Courts',
       'Persons Convicted', 'Persons Discharged', 'Persons Acquitted',
       'Persons in whose cases Trials were completed'], dtype=object)

In [312]:
csv5= csv5.drop(columns=['sl_no'])
csv5.head(3)

        city                         Crime  person_count Arrested_Gender
0       Agra  Notice Issued (Sec. 41 CrPC)          1277            Male
1  Ahmedabad  Notice Issued (Sec. 41 CrPC)           598            Male
2   Amritsar  Notice Issued (Sec. 41 CrPC)           152            Male

In [313]:
u.save_clean(csv5, "data/cleaned/file5.csv")

Saved | shape- (2703, 4)

All datatypes are correct and all necessary changes were made. 

**file5 or csv5 is ready for 03_Analysis.**